FROM ubuntu:18.04

MAINTAINER Viacheslav Blinov "blinov.vyacheslav@gmail.com"

# 0. update repositories
RUN apt-get update
# 1. install tools
RUN apt-get install -y openjdk-8-jdk software-properties-common build-essential make curl wget rpm zip git
